'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Museums',
      [
        {
          name: 'Государственный Эрмитаж',
          description:
            'Эрмитаж - крупный культурный, исторический и художественный комплекс, основанный в 1764 г. по инициативе Екатерины II. Перед посещением Эрмитажа определитесь с приоритетами, экспонатов здесь хватит на 8 лет изучения. Любителей истории привлекут античные залы, ценителям классики понравятся полотна Рембрандта, Рубенса, ван Дейка и других мэтров живописи. Ежегодно в музей привозятся экспонаты с разных точек мира, как современных творцов, так и частные коллекции.',
          location: 'Дворцовая пл., 2',
          city: 'Санкт-Петербург',
          photo: 'http://localhost:3000/museumsImages/1_Эрмитаж.jpg',
          workedTime:
            'вторник, пятница, суббота с 11:00 до 20:00\nсреда, четверг, воскресенье с 11:00 до 18:00',
          holidays: 'понедельник',
          theme: 'Искусство',
          coordinates: '59.94008206417637, 30.312813999999978',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'State Hermitage Museum',
          description_en: 'The Hermitage is a large cultural, historical, and artistic complex founded in 1764 at the initiative of Catherine II...',
          location_en: 'Palace Square 2',
          city_en: 'Saint Petersburg',
          workedTime_en: 'Tuesday, Friday, Saturday from 11:00 to 20:00, Wednesday, Thursday, Sunday from 11:00 to 18:00',
          holidays_en: 'Monday',
          theme_en: 'Art',
          name_de: 'Die Eremitage',
          description_de: 'Die Ermitage ist eines der größten und bedeutendsten Kunstmuseen der Welt. Auch der Gebäudekomplex, der das Museum beherbergt und zu dem der berühmte Winterpalast gehört, wird heute zusammenfassend als Eremitage bezeichnet. Er ist ein zentraler Bestandteil der zum UNESCO-Weltkulturerbe erklärten Sankt Petersburger Innenstadt.',
          location_de: 'Palastplatz, 2',
          city_de: 'Sankt Petersburg',
          workedTime_de: 'Dienstag, Freitag, Samstag von 11:00 bis 20:00, Mittwoch, Donnerstag, Sonntag von 11:00 bis 18:00',
          holidays_de: 'Montag',
          theme_de: 'Kunst',
        },
        {
          name: 'Русский музей',
          description:
            'Российский государственный художественный музей в Санкт-Петербурге, крупнейшее в мире собрание русского изобразительного искусства. Выставочный комплекс современного Русского музея включает пять зданий в исторических районах Санкт-Петербурга: Михайловский дворец с корпусом Бенуа, Михайловский (Инженерный) замок, Мраморный дворец, Строгановский дворец и Летний дворец Петра I.',
          location: 'ул. Инженерная, 4',
          city: 'Санкт-Петербург',
          photo: 'http://localhost:3000/museumsImages/2_РусскийМузей.jpg',
          workedTime:
            'понедельник с 10:00 до 20:00\nсреда, пятница, суббота, воскресенье с 10:00 до 18:00',
          holidays: 'четверг',
          theme: 'Искусство',
          coordinates: '59.938787221245846, 30.33238177103917',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'Russian Museum',
          description_en: 'The Russian State Art Museum in Saint Petersburg is the world\'s largest collection of Russian fine art. The exhibition complex of the modern Russian Museum includes five buildings in historic areas of Saint Petersburg: the Mikhailovsky Palace with the Benois Wing, the Mikhailovsky (Engineering) Castle, the Marble Palace, the Stroganov Palace, and the Summer Palace of Peter I.',
          location_en: 'Engineering Street 4',
          city_en: 'Saint Petersburg',
          workedTime_en: 'Monday from 10:00 to 20:00\nWednesday, Friday, Saturday, Sunday from 10:00 to 18:00',
          holidays_en: 'Thursday',
          theme_en: 'Art',
          name_de: 'Russisches Museum',
          description_de: 'Das Russische Staatliche Kunstmuseum in Sankt Petersburg ist die größte Sammlung russischer Bildender Kunst weltweit. Der moderne Ausstellungskomplex des Russischen Museums umfasst fünf Gebäude in historischen Bezirken von Sankt Petersburg: den Michailowski-Palast mit dem Benois-Flügel, das Michailowski (Ingenieurs-) Schloss, den Marmorpalast, den Stroganow-Palast und den Sommerpalast von Peter I.',
          location_de: 'Ingenieurstraße 4',
          city_de: 'Sankt Petersburg',
          workedTime_de: 'Montag von 10:00 bis 20:00\nMittwoch, Freitag, Samstag, Sonntag von 10:00 bis 18:00',
          holidays_de: 'Donnerstag',
          theme_de: 'Kunst',
        },
        {
          name: 'Музей современного искусства Эрарта',
          description:
            'Эрарта – место, в котором можно встретиться со смелыми экспериментами, инновационными технологиями и необычными, а подчас и шокирующими объектами contemporary art.В России это самый большой музей современного искусства, пребывающий в частной собственности. В нем представлено около 3 тысяч работ известных мировых художников, уникальных авторских проектов и прочих художественных экспозиций. На территории Эрарты работает кинозал, ресторан, сувенирный магазин, проводятся интерактивные развлечения для детей и театральные постановки.',
          location: '29-я линия Васильевского острова, дом 2',
          city: 'Санкт-Петербург',
          photo: 'http://localhost:3000/museumsImages/3_Эрарта.jpg',
          workedTime: 'понедельник, среда, воскресенье с 10:00 до 22:00',
          holidays: 'вторник, четверг, пятница, суббота',
          theme: 'Искусство',
          coordinates: '59.931900, 30.251621',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'Erarta Museum of Contemporary Art',
          description_en: 'Erarta is a place where one can encounter bold experiments, innovative technologies, and unusual, sometimes shocking objects of contemporary art. It is the largest private contemporary art museum in Russia. It features around 3,000 works by renowned artists from around the world, unique author projects, and other art exhibitions. On the territory of Erarta, there is a cinema hall, a restaurant, a souvenir shop, interactive entertainment for children, and theatrical performances.',
          location_en: '29th Line of Vasilyevsky Island 2',
          city_en: 'Saint Petersburg',
          workedTime_en: 'Monday, Wednesday, Sunday from 10:00 to 22:00',
          holidays_en: 'Tuesday, Thursday, Friday, Saturday',
          theme_en: 'Art',
          name_de: 'Erarta Museum für Zeitgenössische Kunst',
          description_de: 'Erarta ist ein Ort, an dem man auf mutige Experimente, innovative Technologien und ungewöhnliche, manchmal schockierende Objekte der zeitgenössischen Kunst trifft. Es ist das größte private Museum für zeitgenössische Kunst in Russland. Es verfügt über etwa 3.000 Werke bekannter internationaler Künstler, einzigartige Autorprojekte und andere künstlerische Exponate. Auf dem Gelände von Erarta gibt es ein Kino, ein Restaurant, einen Souvenirladen, interaktive Kinderaktivitäten und Theatervorstellungen.',
          location_de: '2, 29. Linie der Wassiljewski-Insel',
          city_de: 'Sankt Petersburg',
          workedTime_de: 'Montag, Mittwoch, Sonntag von 10:00 bis 22:00',
          holidays_de: 'Dienstag, Donnerstag, Freitag, Samstag',
          theme_de: 'Kunst',
          },
        {
          name: 'Гранд Макет Россия',
          description:
            'Россия в миниатюре, расположившаяся на площади 800 кв. м, позволяет оценить богатство, красоту и уникальность нашей страны. Изначально музей, созданный за личные деньги одного из местных предпринимателей, должен был отображать только сам Санкт-Петербург. Однако уж на этапе проектирования было решено воссоздать в миниатюре практически всю Россию. Кроме Северной столицы здесь есть Сибирь, Зауралье, Каспий, Сочи и Камчатка, Уральский хребет, Москва, Тайга и Дальний Восток. Сам макет создан в формате единой интерактивной системы, которая передает смену традиций и ландшафтов. Кроме главных российских достопримечательностей на нем можно увидеть сцены из обычной жизни.',
          location: 'улица Цветочная, 16 Л',
          city: 'Санкт-Петербург',
          photo: 'http://localhost:3000/museumsImages/4_ГрандМакет.jpg',
          workedTime: 'ежедневно с 10:00 до 22:00',
          holidays: 'без выходных',
          theme: 'Наука и техника',
          coordinates: '59.888058, 30.331005',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'Grand Maket Russia',
          description_en: 'Russia in miniature, located on an area of 800 square meters, allows you to appreciate the richness, beauty, and uniqueness of our country. Initially, the museum, created with the personal money of one of the local entrepreneurs, was supposed to reflect only Saint Petersburg. However, during the design stage, it was decided to recreate almost all of Russia in miniature. In addition to the Northern Capital, there are Siberia, the Urals, the Caspian Sea, Sochi and Kamchatka, the Ural Mountains, Moscow, the Taiga, and the Far East. The layout is created in the format of a single interactive system that conveys the change of traditions and landscapes. Besides the main Russian landmarks, you can see scenes from ordinary life on it.',
          location_en: 'Tsvetochnaya Street 16 L ',
          city_en: 'Saint Petersburg',
          workedTime_en: 'Daily from 10:00 to 22:00',
          holidays_en: 'No',
          theme_en: 'Science and Technology',
          name_de: 'Grand Maket Russland',
          description_de: 'Russland im Miniaturformat, verteilt auf eine Fläche von 800 Quadratmetern, ermöglicht es Ihnen, den Reichtum, die Schönheit und die Einzigartigkeit unseres Landes zu schätzen. Ursprünglich sollte das Museum, das mit den persönlichen Mitteln eines lokalen Unternehmers gegründet wurde, nur St. Petersburg selbst darstellen. Während der Planungsphase wurde jedoch beschlossen, fast ganz Russland im Miniaturformat nachzubilden. Neben der nördlichen Hauptstadt gibt es hier Sibirien, Trans-Ural, das Kaspische Meer, Sotschi und Kamtschatka, das Uralgebirge, Moskau, Taiga und den Fernen Osten. Das Modell selbst ist als ein interaktives System gestaltet, das den Wechsel der Traditionen und Landschaften vermittelt. Neben den wichtigsten russischen Sehenswürdigkeiten können Sie auch Szenen aus dem Alltag sehen.',
          location_de: '16L Tsvetochnaya St.',
          city_de: 'Sankt Petersburg',
          workedTime_de: 'Täglich von 10:00 bis 22:00',
          holidays_de: 'Keine Ruhetage',
          theme_de: 'Wissenschaft und Technik',
        },
        {
          name: 'Кунсткамера',
          description:
            'Кабинет редкостей или Музей антропологии и этнографии им. Петра Великого был открыт в 1714 году. В основу собрания легла коллекция необычных вещей Петра I, экспонаты свозились со всех концов России. Разнообразные анатомические, зоологические, минералогические и прочие раритеты, которые, по мнению царя, представляли ценность для науки.',
          location: 'Университетская набережная, 3',
          city: 'Санкт-Петербург',
          photo: 'http://localhost:3000/museumsImages/5_Кунсткамера.jpg',
          workedTime: 'ежедневно с 11:00 до 18:00',
          holidays: 'без выходных',
          theme: 'Энтография',
          coordinates: '59.941727, 30.304900',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'Kunstkamera',
          description_en: 'The Cabinet of Curiosities or the Museum of Anthropology and Ethnography named after Peter the Great was opened in 1714. The collection was based on Peter I\'s collection of unusual items, and exhibits were brought from all over Russia. Various anatomical, zoological, mineralogical, and other rarities, which, in the opinion of the tsar, were of scientific value.',
          location_en: 'Universitetskaya Embankment 3',
          city_en: 'Saint Petersburg',
          workedTime_en: 'Daily from 11:00 to 18:00',
          holidays_en: 'No',
          theme_en: 'Ethnography',
          name_de: 'Kunstkamera',
          description_de: 'Die Kunstkamera oder das Museum für Anthropologie und Ethnographie benannt nach Peter dem Großen wurde 1714 eröffnet. Die Sammlung basiert auf den ungewöhnlichen Dingen, die Peter I. gesammelt hatte, und die Exponate wurden aus ganz Russland zusammengetragen. Verschiedene anatomische, zoologische, mineralogische und andere Raritäten, die laut dem Zaren von wissenschaftlichem Wert waren.',
          location_de: '3 Universitätskai',
          city_de: 'Sankt Petersburg',
          workedTime_de: 'Täglich von 11:00 bis 18:00',
          holidays_de: 'Keine Ruhetage',
          theme_de: 'Ethnographie',
        },
        {
          name: 'Зоологический музей ЗИН РАН',
          description:
            'Один из крупнейших зоологических музеев мира. Был основан в 1832 году путем отделения от знаменитой Кунсткамеры. Первые экспозиции состояли из раковин, спиртовых препаратов, кораллов и материалов остеологии, но за практически двух вековую историю эта незначительная коллекция выросла в несколько раз и начала занимать больше 3 десятков залов. Каждый из них посвящен отдельным видам животного мира – насекомым, китообразным, рыбам, земноводным, млекопитающим и другим.',
          location: 'Университетская набережная, дом 1',
          city: 'Санкт-Петербург',
          photo: 'http://localhost:3000/museumsImages/6_Зоологический.jpg',
          workedTime: 'понедельник, среда, воскресенье с 11:00 до 18:00',
          holidays: 'вторник, четверг, пятница, суббота',
          theme: 'Природа и животные',
          coordinates: '59.94264102921577, 30.30594045899961',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'Zoological Museum of the Zoological Institute of the Russian Academy of Sciences',
          description_en: 'One of the largest zoological museums in the world. It was founded in 1832 by separating from the famous Kunstkamera. The first exhibitions consisted of shells, alcohol specimens, corals, and osteology materials, but over nearly two centuries, this insignificant collection has grown several times and began to occupy more than 30 halls. Each of them is dedicated to individual species of the animal world - insects, cetaceans, fish, amphibians, mammals, and others.',
          location_en: 'Universitetskaya Embankment 1',
          city_en: 'Saint Petersburg',
          workedTime_en: 'Monday, Wednesday, Sunday from 11:00 to 18:00',
          holidays_en: 'Tuesday, Thursday, Friday, Saturday',
          theme_en: 'Nature',
          name_de: 'Zoologisches Museum der Russischen Akademie der Wissenschaften',
          description_de: 'Eines der größten zoologischen Museen der Welt. Es wurde 1832 gegründet, indem es von der berühmten Kunstkamera abgetrennt wurde. Die ersten Ausstellungen bestanden aus Muscheln, Spirituosenpräparaten, Korallen und osteologischem Material, aber in fast zwei Jahrhunderten ist diese bescheidene Sammlung mehrfach gewachsen und nimmt nun mehr als 30 Säle ein. Jeder von ihnen ist einer bestimmten Tierart gewidmet – Insekten, Walen, Fischen, Amphibien, Säugetieren und anderen.',
          location_de: 'Universitätskai, Haus 1',
          city_de: 'Sankt Petersburg',
          workedTime_de: 'Montag, Mittwoch, Sonntag von 11:00 bis 18:00',
          holidays_de: 'Dienstag, Donnerstag, Freitag, Samstag',
          theme_de: 'Natur und Tiere',
        },
        {
          name: 'Музей железных дорог России',
          description:
            'Уникальный научно-технический музей, коллекция которого включает в себя 44 инсталляции и 118 экспонатов подвижных составов. В железнодорожном музее хранятся старинные паро-, тепло- и электровозы, а также другая техника, бороздившая по железным дорогам России. В музее регулярно устраивают экскурсии, показы тематического кино и программы для детей, а благодаря реалистичному тренажеру каждый из вас может почувствовать себя настоящим машинистом.',
          location: 'Библиотечный переулок 4, корпус 2',
          city: 'Санкт-Петербург',
          photo: 'http://localhost:3000/museumsImages/7_МузейЖелезныхДорог.jpg',
          workedTime:
            'понедельник, вторник, пятница, воскресенье с 10:30 до 18:00',
          holidays: 'среда, суббота',
          theme: 'Наука и техника',
          coordinates: '59.90557280595487, 30.297786195106493',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'Russian Railway Museum',
          description_en: 'A unique scientific and technical museum, its collection includes 44 installations and 118 rolling stock exhibits. The railway museum houses old steam, diesel, and electric locomotives, as well as other equipment that roamed the railways of Russia. The museum regularly hosts excursions, thematic film screenings, and programs for children, and thanks to a realistic simulator, each of you can feel like a real train driver.',
          location_en: 'Bibliotechny Lane 4, Building 2',
          city_en: 'Saint Petersburg',
          workedTime_en: 'Monday, Tuesday, Friday, Sunday from 10:30 to 18:00',
          holidays_en: 'Wednesday, Saturday',
          theme_en: 'Science and Technology',
          name_de: 'Museum der Russischen Eisenbahnen',
          description_de: 'Ein einzigartiges wissenschaftlich-technisches Museum, dessen Sammlung 44 Installationen und 118 Exponate rollenden Materials umfasst. Im Eisenbahnmuseum sind alte Dampf-, Diesel- und Elektrolokomotiven sowie andere Technik untergebracht, die auf den Eisenbahnen Russlands verkehrten. Im Museum werden regelmäßig Führungen, thematische Filmvorführungen und Programme für Kinder organisiert, und dank eines realistischen Simulators kann sich jeder als echter Lokführer fühlen.',
          location_de: 'Bibliotheksgasse 4, Gebäude 2',
          city_de: 'Sankt Petersburg',
          workedTime_de: 'Montag, Dienstag, Freitag, Sonntag von 10:30 bis 18:00',
          holidays_de: 'Mittwoch, Samstag',
          theme_de: 'Wissenschaft und Technik',
        },
        {
          name: 'Юсуповский дворец',
          description:
            'Резиденция пяти поколений династии князей Юсуповых считается одним из лучших дворцов Петербурга. Она известна не только роскошными интерьерами парадных залов, но и скандальным историческим прошлым: именно в здешнем подвале был убит «злой гений царской семьи» Григорий Распутин.',
          location: 'Набережная реки Мойки, 94',
          city: 'Санкт-Петербург',
          photo: 'http://localhost:3000/museumsImages/8_ЮсуповскийДворец.jpg',
          workedTime: 'вторник - пятница с 10:00 до 19:30',
          holidays: 'понедельник, суббота, воскресенье',
          theme: 'Архитектура',
          coordinates: '59.92938155498306, 30.298848253186247',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'Yusupov Palace',
          description_en: 'The residence of five generations of the Yusupov princes dynasty is considered one of the best palaces in Saint Petersburg. It is known not only for its luxurious interiors of the ceremonial halls but also for its scandalous historical past: it was in the basement here that the "evil genius of the tsar\'s family" Grigory Rasputin was killed.',
          location_en: 'Moika River Embankment 94',
          city_en: 'Saint Petersburg',
          workedTime_en: 'Tuesday - Friday from 10:00 to 19:30',
          holidays_en: 'Monday, Saturday, Sunday',
          theme_en: 'Architecture',
          name_de: 'Jussupow-Palast',
          description_de: 'Die Residenz von fünf Generationen der Fürstendynastie Jussupow gilt als einer der besten Paläste von St. Petersburg. Sie ist bekannt nicht nur für ihre prächtigen Interieurs der Paradesäle, sondern auch für ihre skandalöse historische Vergangenheit: Hier im Keller wurde der "böse Geist der Zarenfamilie" Grigori Rasputin ermordet.',
          location_de: 'Moika-Uferstraße, 94',
          city_de: 'Sankt Petersburg',
          workedTime_de: 'Dienstag - Freitag von 10:00 bis 19:30',
          holidays_de: 'Montag, Samstag, Sonntag',
          theme_de: 'Architektur',
        },
        {
          name: 'Музей Пушкина',
          description:
            'В рейтинг лучших музеев СПб входит и мемориальная квартира Пушкина, с которой связана не только трагическая судьба великого поэта, но и становление всей русской литературы. Именно в этом месте Александр Сергеевич провел последние месяцы своей жизни и именно тут скончался после дуэли с Дантесом. Интерьер этой квартиры максимально повторяет реальную обстановку. Здесь сохранилось немало предметов, связанных с жизнью и смертью поэта, – прядь его волос, посмертная маска, личные вещи супруги, портреты детей, гравюры, жилет со следами крови и даже диван, на котором умер основоположник русского реализма.',
          location: 'Набережная реки Мойки, 12',
          city: 'Санкт-Петербург',
          photo: 'http://localhost:3000/museumsImages/9_МузейПушкинаСпб.jpg',
          workedTime: 'понедельник, среда, воскресенье с 10:00 до 18:00',
          holidays: 'вторник, четверг, пятница, суббота',
          theme: 'История',
          coordinates: '59.94116347609452, 30.32130479265976',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'Pushkin Museum',
          description_en: 'Among the best museums in Saint Petersburg is the memorial apartment of Pushkin, which is associated not only with the tragic fate of the great poet but also with the formation of all Russian literature. It was in this place that Alexander Sergeevich spent the last months of his life and died here after the duel with Dantes. The interior of this apartment maximally repeats the real situation. Many items related to the life and death of the poet have been preserved here – a lock of his hair, a death mask, his wife\'s personal belongings, portraits of his children, engravings, a vest with bloodstains, and even the sofa on which the founder of Russian realism died.',
          location_en: 'Moika River Embankment 12',
          city_en: 'Saint Petersburg',
          workedTime_en: 'Monday, Wednesday, Sunday from 10:00 to 18:00',
          holidays_en: 'Tuesday, Thursday, Friday, Saturday',
          theme_en: 'History',
          name_de: 'Puschkin-Museum',
          description_de: 'Zu den besten Museen von St. Petersburg gehört auch die Gedenkwohnung von Puschkin, die nicht nur mit dem tragischen Schicksal des großen Dichters, sondern auch mit der Entstehung der gesamten russischen Literatur verbunden ist. Genau hier verbrachte Alexander Sergejewitsch seine letzten Lebensmonate und genau hier starb er nach dem Duell mit Dantes. Das Interieur dieser Wohnung reproduziert die reale Umgebung so genau wie möglich. Hier sind viele Gegenstände erhalten, die mit dem Leben und Tod des Dichters verbunden sind – eine Locke seines Haares, die Totenmaske, persönliche Gegenstände seiner Frau, Porträts der Kinder, Radierungen, eine Weste mit Blutspuren und sogar das Sofa, auf dem der Begründer des russischen Realismus starb.',
          location_de: 'Moika-Uferstraße, 12',
          city_de: 'Sankt Petersburg',
          workedTime_de: 'Montag, Mittwoch, Sonntag von 10:00 bis 18:00',
          holidays_de: 'Dienstag, Donnerstag, Freitag, Samstag',
          theme_de: 'Berühmte Persönlichkeiten',
        },
        {
          name: 'Военно-морской музей',
          description:
            'Старейший музей России, основанный в начале 18 века по приказу Петра I. Представляет собой крупнейшее хранилище уникальных военно-морских экспонатов. Их здесь больше 700 тысяч! Многие предметы являются личной собственностью самого императора и известных адмиралов. Помимо основной экспозиции, площадь которой составляет около 8 тысяч кв. м., Военно-морской музей имеет 6 филиалов: крепость в Кронштадте, музей Балтийского флота, судно «Михаил Кутузов», Дорога жизни на Ладожском озере, субмарина «Народоволец» и уже известный вам крейсер «Аврора».',
          location: 'площадь Труда, 5',
          city: 'Санкт-Петербург',
          photo:
            'http://localhost:3000/museumsImages/10_ВоенноМорскойМузей.jpg',
          workedTime: 'среда - воскресенье с 11:00 до 18:00',
          holidays: 'понедельник, вторник',
          theme: 'История',
          coordinates: '59.929539174633874, 30.2935662496681',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'Naval Museum',
          description_en: 'The oldest museum in Russia, founded in the early 18th century by the order of Peter I. It is the largest repository of unique naval exhibits. There are more than 700 thousand of them here! Many items are the personal property of the emperor himself and famous admirals. In addition to the main exhibition, which occupies about 8 thousand square meters, the Naval Museum has 6 branches: the fortress in Kronstadt, the Baltic Fleet Museum, the ship "Mikhail Kutuzov", the Road of Life on Lake Ladoga, the submarine "Narodovolets" and the already known cruiser "Aurora".',
          location_en: 'Truda Square 5',
          city_en: 'Saint Petersburg',
          workedTime_en: 'Wednesday - Sunday from 11:00 to 18:00',
          holidays_en: 'Monday, Tuesday',
          theme_en: 'History',
          name_de: 'Marinemuseum',
          description_de: 'Das älteste Museum Russlands, gegründet zu Beginn des 18. Jahrhunderts auf Befehl von Peter I. Es ist das größte Depot einzigartiger marinehistorischer Exponate. Es gibt mehr als 700.000 davon! Viele Gegenstände sind persönliches Eigentum des Kaisers selbst und bekannter Admiräle. Neben der Hauptausstellung, die eine Fläche von etwa 8.000 Quadratmetern umfasst, verfügt das Marinemuseum über 6 Filialen: die Festung Kronstadt, das Museum der Baltischen Flotte, das Schiff "Mikhail Kutuzov", der Weg des Lebens am Ladogasee, das U-Boot "Narodovolets" und der bereits bekannte Kreuzer "Aurora".',
          location_de: 'Trud-Platz, 5',
          city_de: 'Sankt Petersburg',
          workedTime_de: 'Mittwoch - Sonntag von 11:00 bis 18:00',
          holidays_de: 'Montag, Dienstag',
          theme_de: 'Geschichte',
        },
        {
          name: 'Российский этнографический музей',
          description:
            'Российский этнографический музей (РЭМ) часто называют главной сокровищницей народной культуры. В его галереях и залах собрана большая коллекция, посвященная костюмам, истории, промыслам и прикладному искусству. В музее представлены все этносы, которые когда-либо жили на Руси, в СССР и современной России - от Дальнего Востока и Забайкалья до Сибири и Урала. Все вещи РЭМа подлинные. Их собирало не одно поколение музейных сотрудников прямо в среде обитания самих народов. Помимо прочего именно здесь находится знаменитый Мраморный зал, считающийся одним из самых красивых в Санкт-Петербурге.',
          location: 'улица Инженерная, дом 4, корпус 1',
          city: 'Санкт-Петербург',
          photo:
            'http://localhost:3000/museumsImages/11_ЭтнографическийМузей.jpg',
          workedTime: 'вторник - воскресенье с 10:00 до 21:00',
          holidays: 'понедельник',
          theme: 'Этнография',
          coordinates: '59.93788322328683, 30.33437829066848',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'Russian Ethnographic Museum',
          description_en: 'The Russian Ethnographic Museum (REM) is often called the main treasury of folk culture. Its galleries and halls house a large collection dedicated to costumes, history, crafts, and applied arts. The museum presents all ethnic groups that ever lived in Russia, the USSR, and modern Russia - from the Far East and Transbaikalia to Siberia and the Urals. All REM items are genuine. They were collected by more than one generation of museum staff directly in the habitats of the peoples themselves. In addition, it is here that the famous Marble Hall is located, considered one of the most beautiful in Saint Petersburg.',
          location_en: 'Engineering Street 4, Building 1',
          city_en: 'Saint Petersburg',
          workedTime_en: 'Tuesday - Sunday from 10:00 to 21:00',
          holidays_en: 'Monday',
          theme_en: 'Ethnography',
          name_de: 'Russisches Ethnographisches Museum',
          description_de: 'Das Russische Ethnographische Museum (REM) wird oft als die Hauptschatzkammer der Volkskultur bezeichnet. In seinen Galerien und Hallen ist eine große Sammlung versammelt, die Kostümen, Geschichte, Handwerken und angewandter Kunst gewidmet ist. Im Museum sind alle Ethnien vertreten, die jemals in Russland, der UdSSR und dem modernen Russland gelebt haben - vom Fernen Osten und Transbaikalien bis Sibirien und dem Ural. Alle Gegenstände des REM sind echt. Sie wurden von mehreren Generationen von Museumsmitarbeitern direkt in den Lebensräumen der Völker gesammelt. Unter anderem befindet sich hier auch der berühmte Marmorsaal, der als einer der schönsten in Sankt Petersburg gilt.',
          location_de: 'Ingenieurstraße 4, Gebäude 1',
          city_de: 'Sankt Petersburg',
          workedTime_de: 'Dienstag - Sonntag von 10:00 bis 21:00',
          holidays_de: 'Montag',
          theme_de: 'Ethnographie',
        },
        {
          name: 'Исакиевский собор',
          description:
            'Музей в Исаакиевском соборе появился еще в первой половине 20 в. Поначалу в нем размещалась только одна выставка, посвященная строительству этого здания. Сейчас это целый музейный комплекс, в состав которого входит еще 2 сооружения – Спас на крови и дьяконник храма Воскресения Христова. В основе музейной коллекции лежат графика, мозаика, старинные книги, скульптура и предметы прикладного искусства.',
          location: 'Исаакиевская пл., 4',
          city: 'Санкт-Петербург',
          photo: 'http://localhost:3000/museumsImages/12_ИсаакиевскийСобор.jpg',
          workedTime: 'ежедневно с 10:00 до 18:00',
          holidays: 'без выходных',
          theme: 'Архитектура',
          coordinates: '59.93410133118889, 30.306129160713184',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'Saint Isaac\'s Cathedral',
          description_en: 'The museum in Saint Isaac\'s Cathedral appeared in the first half of the 20th century. Initially, it housed only one exhibition dedicated to the construction of this building. Now it is a whole museum complex, which includes two more structures - the Savior on Spilled Blood and the Deacon of the Church of the Resurrection of Christ. The museum collection is based on graphics, mosaics, old books, sculptures, and applied art objects.',
          location_en: 'Saint Isaac\'s Square 4',
          city_en: 'Saint Petersburg',
          workedTime_en: 'Daily from 10:00 to 18:00',
          holidays_en: 'No',
          theme_en: 'Architecture',
          name_de: 'Isaakskathedrale',
          description_de: 'Das Museum in der Isaakskathedrale entstand in der ersten Hälfte des 20. Jahrhunderts. Anfangs gab es nur eine Ausstellung, die dem Bau dieses Gebäudes gewidmet war. Heute ist es ein ganzer Museumskomplex, der zwei weitere Gebäude umfasst – die Auferstehungskirche und das Diakonat der Kirche der Auferstehung Christi. Die Museumssammlung umfasst Grafiken, Mosaike, alte Bücher, Skulpturen und angewandte Kunstwerke.',
          location_de: 'Isaaksplatz, 4',
          city_de: 'Sankt Petersburg',
          workedTime_de: 'Täglich von 10:00 bis 18:00',
          holidays_de: 'Keine Ruhetage',
          theme_de: 'Architektur',
        },
        {
          name: 'Ботанический сад',
          description:
            'Ботанический сад Петра Великого был открыт в 1823 году. В прежние времена в нем выращивали лекарственные растения для полевых и казенных аптек. Сейчас здесь можно увидеть огромную коллекцию экспонатов, собранную трудами выдающихся российских ученых. Это и редкие растения, привезенные с разных уголков земли, и образцы древесины, и сама крупная в мире кувшинка, и собрание семян.',
          location: 'улица профессора Попова, 2',
          city: 'Санкт-Петербург',
          photo:
            'http://localhost:3000/museumsImages/13_БотаническийСадСпб.jpg',
          workedTime: 'ежедневно с 10:00 до 17:00',
          holidays: 'без выходных',
          theme: 'Природа и животные',
          coordinates: '59.97118930289723, 30.322867319315282',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'Botanical Garden',
          description_en: 'The Botanical Garden of Peter the Great was opened in 1823. In earlier times, medicinal plants were grown there for field and state pharmacies. Now you can see a huge collection of exhibits gathered by the efforts of outstanding Russian scientists. These are rare plants brought from different parts of the world, samples of wood, the largest water lily in the world, and a collection of seeds.',
          location_en: 'Professor Popov Street 2',
          city_en: 'Saint Petersburg',
          workedTime_en: 'Daily from 10:00 to 17:00',
          holidays_en: 'No',
          theme_en: 'Nature',
          name_de: 'Botanischer Garten',
          description_de: 'Der Botanische Garten Peter des Großen wurde 1823 eröffnet. Früher wurden hier Heilpflanzen für Feld- und Staatsapotheken angebaut. Heute können Sie hier eine riesige Sammlung von Exponaten sehen, die durch die Arbeit herausragender russischer Wissenschaftler zusammengetragen wurden. Dazu gehören seltene Pflanzen, die aus verschiedenen Teilen der Welt mitgebracht wurden, Holzproben, die größte Seerose der Welt und eine Samensammlung.',
          location_de: 'Professor-Popow-Straße, 2',
          city_de: 'Sankt Petersburg',
          workedTime_de: 'Täglich von 10:00 bis 17:00',
          holidays_de: 'Keine Ruhetage',
          theme_de: 'Natur und Tiere',
        },
        {
          name: 'Музей Фаберже',
          description:
            'Один из лучших частных музеев Питера. Находится во дворце Нарышкиных-Шуваловых, который представляет собой яркий образец русской архитектуры. Экспонаты, собранные в стенах музея, считаются уникальными и не имеют аналогов в мире. Особого внимания среди них заслуживают 9 пасхальных яиц, 2 из которых принадлежат знаменитой компании Фаберже. Кроме этих исторических артефактов в музее представлено собрание драгоценных изделий и прикладного искусства конца 19 – начала 20 веков.',
          location: 'Набережная реки Фонтанки, 21',
          city: 'Санкт-Петербург',
          photo: 'http://localhost:3000/museumsImages/14_МузейФаберже.jpg',
          workedTime: 'ежедневно с 10:00 до 21:00',
          holidays: 'без выходных',
          theme: 'Искусство',
          coordinates: '59.934716608347905, 30.343139269346207',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'Faberge Museum',
          description_en: 'One of the best private museums in Saint Petersburg. It is located in the Naryshkin-Shuvalov Palace, which is a vivid example of Russian architecture. The exhibits collected within the walls of the museum are considered unique and have no analogs in the world. Of particular interest among them are 9 Easter eggs, 2 of which belong to the famous Faberge company. In addition to these historical artifacts, the museum features a collection of precious items and applied art from the late 19th - early 20th centuries.',
          location_en: 'Fontanka River Embankment 21',
          city_en: 'Saint Petersburg',
          workedTime_en: 'Daily from 10:00 to 21:00',
          holidays_en: 'No',
          theme_en: 'Art',
          name_de: 'Fabergé-Museum',
          description_de: 'Eines der besten privaten Museen in Sankt Petersburg. Es befindet sich im Narischkin-Schuwalow-Palast, der ein herausragendes Beispiel russischer Architektur darstellt. Die in den Mauern des Museums gesammelten Exponate gelten als einzigartig und haben keine Analoga in der Welt. Besonders bemerkenswert sind 9 Ostereier, von denen 2 der berühmten Firma Fabergé gehören. Neben diesen historischen Artefakten gibt es im Museum eine Sammlung von Schmuckstücken und angewandter Kunst aus dem späten 19. und frühen 20. Jahrhundert.',
          location_de: 'Fontanka-Kai, 21',
          city_de: 'Sankt Petersburg',
          workedTime_de: 'Täglich von 10:00 bis 21:00',
          holidays_de: 'Keine Ruhetage',
          theme_de: 'Kunst',
        },
        {
          name: 'Крейсер Аврора',
          description:
            'Если вы не знаете, какие музеи открыты сейчас, обратите внимание на легендарный крейсер, участвовавший в главных морских битвах І мировой войны и являющийся главным символом великой Октябрьской революции.Боевую службу на борту этого судна несут до этой поры. Впрочем, это не мешает посетителям подниматься в корабельный музей и знакомиться с его уникальными экспонатами. На крейсере можно увидеть старинную радиостанцию, котельное и машинное отделение, письма, приказы, снимки и личные вещи экипажа, под которые выделен отдельный зал.',
          location: 'Петроградская набережная, 2',
          city: 'Санкт-Петербург',
          photo: 'http://localhost:3000/museumsImages/15_КрейсерАврора.jpg',
          workedTime: 'среда - воскресенье с 11:00 до 18:00',
          holidays: 'понедельник, вторник',
          theme: 'История',
          coordinates: '59.95548999626299, 30.337843876335143',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'Cruiser Aurora',
          description_en: 'If you do not know which museums are open now, pay attention to the legendary cruiser that participated in the main naval battles of World War I and is the main symbol of the Great October Revolution. Combat duty is still carried out on board this ship. However, this does not prevent visitors from boarding the ship museum and getting acquainted with its unique exhibits. On the cruiser, you can see an old radio station, boiler and engine rooms, letters, orders, photographs, and personal belongings of the crew, which are allocated a separate room.',
          location_en: 'Petrovskaya Embankment 2',
          city_en: 'Saint Petersburg',
          workedTime_en: 'Wednesday - Sunday from 11:00 to 18:00',
          holidays_en: 'Monday, Tuesday',
          theme_en: 'History',
          name_de: 'Kreuzer Aurora',
          description_de: 'Wenn Sie nicht wissen, welche Museen jetzt geöffnet sind, beachten Sie den legendären Kreuzer, der an den wichtigsten Seeschlachten des Ersten Weltkriegs teilgenommen hat und das Hauptsymbol der großen Oktoberrevolution ist. Der Kampfdienst an Bord dieses Schiffes dauert bis heute an. Dies hindert die Besucher jedoch nicht daran, in das Schiffsmuseum aufzusteigen und sich mit seinen einzigartigen Exponaten vertraut zu machen. Auf dem Kreuzer können Sie ein altes Funkgerät, den Kessel- und Maschinenraum, Briefe, Befehle, Fotos und persönliche Gegenstände der Besatzung sehen, die in einem separaten Raum ausgestellt sind.',
          location_de: 'Petrogradskaja Uferstraße, 2',
          city_de: 'Sankt Petersburg',
          workedTime_de: 'Mittwoch - Sonntag von 11:00 bis 18:00',
          holidays_de: 'Montag, Dienstag',
          theme_de: 'Geschichte',
        },
        {
          name: 'Государственная Третьяковская галерея',
          description:
            'В экспозиции музея представлена одна из крупнейших коллекций русского искусства XI – начала XX века. Третьяковская галерея начала свою историю в 1856 году, когда коллекционер и меценат – Павел Михайлович Третьяков, начал собирать свою коллекцию живописи. Через 10 лет состоялось открытие галереи, где собрание Третьякова насчитывало уже 1800 предметов искусства, а вскоре он принял решение отдать галерею в дар городу. На протяжении многих лет росла не только коллекция искусства, но и количество зданий Третьяковки, но историческое здание в Лаврушинском переулке осталось главным центром галереи. Здесь выставлены легендарные творения таких мастеров, как Рублёв, Репин, Куинджи и Васнецов. Именно в Третьяковской галерее у вас будет возможность пересчитать медведей на картине «Утро в сосновом лесу» Шишкина, ознакомится со знаменитой картиной Серова – «Девочка с персиками», и конечно, восхититься мощными стихиями на полотнах Айвазовского.',
          location: 'Лаврушинский переулок, 10',
          city: 'Москва',
          photo:
            'http://localhost:3000/museumsImages/16_ТретьяковскаяГалерея.jpg',
          workedTime: 'вторник, среда, суббота, воскресенье с 10:00 до 18:00',
          holidays: 'понедельник, четверг',
          theme: 'Искусство',
          coordinates: '55.74150506899968, 37.620042499999975',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'State Tretyakov Gallery',
          description_en: 'The museum\'s exposition presents one of the largest collections of Russian art of the 11th - early 20th century. The Tretyakov Gallery began its history in 1856 when collector and philanthropist Pavel Mikhailovich Tretyakov began collecting his collection of paintings. Ten years later, the gallery opened, where Tretyakov\'s collection already numbered 1,800 works of art, and soon he decided to donate the gallery to the city. Over the years, the collection of art and the number of buildings of the Tretyakov Gallery grew, but the historic building in Lavrushinsky Lane remained the main center of the gallery. Here are exhibited the legendary works of masters such as Rublev, Repin, Kuindzhi, and Vasnetsov. It is in the Tretyakov Gallery that you will have the opportunity to count the bears in Shishkin\'s painting "Morning in a Pine Forest", get acquainted with Serov\'s famous painting "Girl with Peaches", and, of course, admire the powerful elements in Aivazovsky\'s paintings.',
          location_en: 'Lavrushinsky Lane 10',
          city_en: 'Moscow',
          workedTime_en: 'Tuesday, Wednesday, Saturday, Sunday from 10:00 to 18:00',
          holidays_en: 'Monday, Thursday',
          theme_en: 'Art',
          name_de: 'Staatliche Tretjakow-Galerie',
          description_de: 'Die Ausstellung des Museums präsentiert eine der größten Sammlungen russischer Kunst vom 11. bis Anfang des 20. Jahrhunderts. Die Tretjakow-Galerie begann ihre Geschichte im Jahr 1856, als der Sammler und Mäzen Pawel Michailowitsch Tretjakow begann, seine Kunstsammlung zu sammeln. 10 Jahre später wurde die Galerie eröffnet, in der Tretjakows Sammlung bereits 1800 Kunstwerke umfasste, und bald entschloss er sich, die Galerie der Stadt zu schenken. Im Laufe der Jahre wuchs nicht nur die Kunstsammlung, sondern auch die Anzahl der Gebäude der Tretjakow-Galerie, aber das historische Gebäude in der Lawruschinski-Gasse blieb das Hauptzentrum der Galerie. Hier sind legendäre Werke von Meistern wie Rubljow, Repin, Kuindzhi und Wasnezow ausgestellt. In der Tretjakow-Galerie haben Sie die Möglichkeit, die Bären auf dem Gemälde "Morgen im Kiefernwald" von Schischkin zu zählen, das berühmte Gemälde "Mädchen mit Pfirsichen" von Serow zu sehen und sich natürlich von den mächtigen Elementen auf den Leinwänden von Aiwasowski beeindrucken zu lassen.',
          location_de: 'Lawruschinski-Gasse, 10',
          city_de: 'Moskau',
          workedTime_de: 'Dienstag, Mittwoch, Samstag, Sonntag von 10:00 bis 18:00',
          holidays_de: 'Montag, Donnerstag',
          theme_de: 'Kunst',
        },
        {
          name: 'Новая Третьяковка',
          description:
            'На Крымском валу расположено еще одно здание Третьяковской галереи, которое организует крупные выставки российских и международных художников разных эпох. Так за последнее время в галерее выставлялись картины Эдварда Мунка с его знаменитой работой «Крик», великие шедевры Ильи Репина и экспозиция, посвященная творчеству режиссера–философа Андрея Тарковского. На постоянной экспозиции вы можете увидеть сразу два «Черных квадрата» Малевича, ознакомится с творчеством русского авангардиста Владимира Татлина и посмотреть на шедевры Кандинского. Кстати, здание галереи расположено в парке искусств «Музеон», в котором расположено более 800 необычных скульптур. Так что поход в Третьяковскую галерею можно совместить с еще одним интересным местом.',
          location: 'Крымский Вал, 10, Парк искусств «Музеон»',
          city: 'Москва',
          photo: 'http://localhost:3000/museumsImages/17_НоваяТретьяковка.jpg',
          workedTime:
            'понедельник, среда, четверг, воскресенье с 11:00 до 20:00',
          holidays: 'вторник, суббота',
          theme: 'Искусство',
          coordinates: '55.73472327808979, 37.60598307672118',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'New Tretyakov Gallery',
          description_en: 'On Krymsky Val there is another building of the Tretyakov Gallery, which organizes large exhibitions of Russian and international artists of different eras. Thus, recently, the gallery has exhibited paintings by Edvard Munch with his famous work "The Scream", the great masterpieces of Ilya Repin, and an exhibition dedicated to the work of the director-philosopher Andrei Tarkovsky. In the permanent exhibition, you can see two "Black Squares" by Malevich, get acquainted with the work of the Russian avant-garde artist Vladimir Tatlin, and see the masterpieces of Kandinsky. By the way, the gallery building is located in the "Muzeon" art park, which houses more than 800 unusual sculptures. So a visit to the Tretyakov Gallery can be combined with another interesting place.',
          location_en: 'Krymsky Val 10, Muzeon Park of Arts',
          city_en: 'Moscow',
          workedTime_en: 'Monday, Wednesday, Thursday, Sunday from 11:00 to 20:00',
          holidays_en: 'Tuesday, Saturday',
          theme_en: 'Art',
          name_de: 'Neue Tretjakow-Galerie',
          description_de: 'Am Krymski-Wal befindet sich ein weiteres Gebäude der Tretjakow-Galerie, das große Ausstellungen russischer und internationaler Künstler verschiedener Epochen organisiert. In letzter Zeit wurden in der Galerie Gemälde von Edvard Munch mit seinem berühmten Werk "Der Schrei", große Meisterwerke von Ilja Repin und eine Ausstellung über das Werk des Regisseurs und Philosophen Andrei Tarkowski ausgestellt. In der Dauerausstellung können Sie gleich zwei "Schwarze Quadrate" von Malewitsch sehen, sich mit dem Werk des russischen Avantgardisten Wladimir Tatlin vertraut machen und die Meisterwerke von Kandinsky betrachten. Übrigens befindet sich das Galeriegebäude im Kunstpark "Muzeon", in dem mehr als 800 ungewöhnliche Skulpturen zu sehen sind. Ein Besuch der Tretjakow-Galerie kann also mit einem weiteren interessanten Ort verbunden werden.',
          location_de: 'Krymski-Wal, 10, Kunstpark "Muzeon"',
          city_de: 'Moskau',
          workedTime_de: 'Montag, Mittwoch, Donnerstag, Sonntag von 11:00 bis 20:00',
          holidays_de: 'Dienstag, Samstag',
          theme_de: 'Kunst',
        },
        {
          name: 'Государственный музей изобразительных искусств имени А. С. Пушкина',
          description:
            'Государственный музей изобразительных искусств им. А.С. Пушкина известен в первую очередь, крупнейшей коллекцией зарубежного изобразительного искусства в России. У него, как и у Третьяковской галереи есть несколько зданий, но мы остановимся на двух наиболее значимых. В главном здании, которое снаружи выглядит как античный храм, находится основная коллекция музея, включающая в себя искусство Древнего мира, Средневековья и Возрождения, а также полотна европейских художников 17–19 века. Гуляя по музею, у вас будет возможность посетить целые залы, посвященные работам Микеланджело и Рембрандта, посмотреть на античные статуи греческих богов и вдохновится картинами Тициана, Брейгеля и Рубенса.',
          location: 'улица Волхонка, 12 и Волхонка, 14',
          city: 'Москва',
          photo:
            'http://localhost:3000/museumsImages/18_МузейПушкинаМосква.jpg',
          workedTime: 'вторник, пятница, четверг, суббота с 10:00 до 18:00',
          holidays: 'понедельник, среда, воскресенье',
          theme: 'Искусство',
          coordinates: '55.74722588716961, 37.60524446197122',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'State Museum of Fine Arts named after A.S. Pushkin',
          description_en: 'The State Museum of Fine Arts named after A.S. Pushkin is known primarily for the largest collection of foreign fine art in Russia. Like the Tretyakov Gallery, it has several buildings, but we will focus on the two most significant ones. In the main building, which looks like an ancient temple from the outside, is the main collection of the museum, which includes the art of the Ancient World, the Middle Ages, and the Renaissance, as well as paintings by European artists of the 17th-19th centuries. Walking through the museum, you will have the opportunity to visit entire halls dedicated to the works of Michelangelo and Rembrandt, look at ancient statues of Greek gods, and be inspired by the paintings of Titian, Brueghel, and Rubens.',
          location_en: 'Volkhonka Street 12 and 14',
          city_en: 'Moscow',
          workedTime_en: 'Tuesday, Friday, Thursday, Saturday from 10:00 to 18:00',
          holidays_en: 'Monday, Wednesday, Sunday',
          theme_en: 'Art',
          name_de: 'Staatliches Museum der Bildenden Künste benannt nach A. S. Puschkin',
          description_de: 'Das Staatliche Museum der Bildenden Künste benannt nach A.S. Puschkin ist vor allem für seine größte Sammlung ausländischer Bildender Kunst in Russland bekannt. Wie die Tretjakow-Galerie verfügt es über mehrere Gebäude, aber wir konzentrieren uns auf zwei der wichtigsten. Im Hauptgebäude, das von außen wie ein antiker Tempel aussieht, befindet sich die Hauptsammlung des Museums, die Kunst der Antike, des Mittelalters und der Renaissance sowie Werke europäischer Künstler des 17.–19. Jahrhunderts umfasst. Beim Rundgang durch das Museum haben Sie die Möglichkeit, ganze Säle zu besuchen, die den Werken von Michelangelo und Rembrandt gewidmet sind, antike Statuen griechischer Götter zu sehen und sich von den Gemälden von Tizian, Brueghel und Rubens inspirieren zu lassen.',
          location_de: 'Wolchonka-Straße, 12 und Wolchonka-Straße, 14',
          city_de: 'Moskau',
          workedTime_de: 'Dienstag, Freitag, Donnerstag, Samstag von 10:00 bis 18:00',
          holidays_de: 'Montag, Mittwoch, Sonntag',
          theme_de: 'Kunst',
        },
        {
          name: 'Музей современного искусства Гараж',
          description:
            'Музей, основанный Романов Абрамовичем и Дарьей Жуковой, представляет ведущих современных художников со всего мира. За прошедшие несколько лет музей принимал таких значимых артистов современности, как Такаси Мураками, Яеи Кусама, Павел Пепперштейн и Луиз Буржуа. В данный момент Гараж подготовил грандиозную экспозицию, посвященную проблемам в экологии и вопросам о нашем будущем. Также, в здесь проводятся образовательные курсы, лекции и кинопоказы. В музее работает книжный магазин, где можно приобрести современные и актуальные издания, посвященные российскому и мировому искусству, а также кафе с авторской кухней.',
          location: 'улица Крымский Вал, 9, строение 4. Парк Горького',
          city: 'Москва',
          photo: 'http://localhost:3000/museumsImages/19_Гараж.jpg',
          workedTime: 'ежедневно с 11:00 до 22:00',
          holidays: 'без выходных',
          theme: 'Искусство',
          coordinates: '55.727768356054106, 37.601519316522875',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'Garage Museum of Contemporary Art',
          description_en: 'The museum, founded by Roman Abramovich and Daria Zhukova, presents leading contemporary artists from around the world. Over the past few years, the museum has hosted such significant contemporary artists as Takashi Murakami, Yayoi Kusama, Pavel Pepperstein, and Louise Bourgeois. At the moment, Garage has prepared a grandiose exhibition dedicated to environmental issues and questions about our future. Also, educational courses, lectures, and film screenings are held here. The museum has a bookstore where you can purchase modern and relevant publications dedicated to Russian and world art, as well as a cafe with author\'s cuisine.',
          location_en: 'Krymsky Val Street 9, Building 4, Gorky Park',
          city_en: 'Moscow',
          workedTime_en: 'Daily from 11:00 to 22:00',
          holidays_en: 'No',
          theme_en: 'Art',
          name_de: 'Garage Museum für Zeitgenössische Kunst',
          description_de: 'Das von Roman Abramowitsch und Darja Schukowa gegründete Museum präsentiert führende zeitgenössische Künstler aus aller Welt. In den letzten Jahren hat das Museum bedeutende zeitgenössische Künstler wie Takashi Murakami, Yayoi Kusama, Pavel Pepperstein und Louise Bourgeois empfangen. Derzeit hat Garage eine grandiose Ausstellung vorbereitet, die sich mit ökologischen Problemen und Fragen unserer Zukunft befasst. Darüber hinaus werden hier Bildungskurse, Vorlesungen und Filmvorführungen angeboten. Im Museum gibt es einen Buchladen, in dem Sie moderne und aktuelle Veröffentlichungen über russische und internationale Kunst kaufen können, sowie ein Café mit Autorenküche.',
          location_de: 'Krymski-Wal-Straße, 9, Gebäude 4. Gorki-Park',
          city_de: 'Moskau',
          workedTime_de: 'Täglich von 11:00 bis 22:00',
          holidays_de: 'Keine Ruhetage',
          theme_de: 'Kunst',
        },
        {
          name: 'Московский музей современного искусства',
          description:
            'Московский музей современного искусства или кратко – «MMoMa» стал первым в России музеем, который сосредоточился только на современном искусстве. Это стало возможно благодаря знаменитому скульптору и живописцу – Зурабу Церетели, который выставил на публику свою личную коллекцию, насчитывающую более 2000 работ художников 20 века. В ней были представлены работы Малевича, Шагала и Кандинского, а также картины зарубежных художников – Пикассо, Миро и Дали. Сейчас экспозиции музея представлены в четырех зданиях, а основное здание, в котором размещается постоянная экспозиция и проводятся временные выставки, расположено по адресу – улица Петровка, 25. Также, у здания музея находится необычный двор, в котором можно посмотреть на многие скульптуры самого Зураба Церетели, а вход в него бесплатный',
          location:
            'улица Петровка, 25, Ермолаевский переулок, 17, Гоголевский бульвар, 10 и Тверской бульвар, 9',
          city: 'Москва',
          photo:
            'http://localhost:3000/museumsImages/20_МосковскийМузейСовременногоИскусства.jpg',
          workedTime:
            'понедельник - среда, пятница - воскресенье с 12:00 до 20:00',
          holidays: 'четверг',
          theme: 'Искусство',
          coordinates: '55.76701365379201, 37.61423938801853',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'Moscow Museum of Modern Art',
          description_en: 'The Moscow Museum of Modern Art, or "MMoMa" for short, became the first museum in Russia to focus solely on contemporary art. This became possible thanks to the famous sculptor and painter Zurab Tsereteli, who exhibited his personal collection to the public, which numbered more than 2,000 works by 20th-century artists. It featured works by Malevich, Chagall, and Kandinsky, as well as paintings by foreign artists - Picasso, Miro, and Dali. Now the museum\'s exhibitions are presented in four buildings, and the main building, where the permanent exhibition is located and temporary exhibitions are held, is located at 25 Petrovka Street. Also, the museum building has an unusual courtyard where you can see many sculptures by Zurab Tsereteli himself, and entrance is free.',
          location_en: 'Petrovka Street 25, 17 Ermolaevsky Lane, 10 Gogolevsky Boulevard, and 9 Tverskoy Boulevard',
          city_en: 'Moscow',
          workedTime_en: 'Monday - Wednesday, Friday - Sunday from 12:00 to 20:00',
          holidays_en: 'Thursday',
          theme_en: 'Art',
          name_de: 'Moskauer Museum für Zeitgenössische Kunst',
          description_de: 'Das Moskauer Museum für Zeitgenössische Kunst oder kurz "MMoMA" wurde das erste Museum in Russland, das sich ausschließlich auf zeitgenössische Kunst konzentrierte. Dies wurde dank des berühmten Bildhauers und Malers Zurab Tsereteli möglich, der seine persönliche Sammlung mit über 2000 Werken von Künstlern des 20. Jahrhunderts der Öffentlichkeit zugänglich machte. In ihr waren Werke von Malewitsch, Schagall und Kandinsky sowie Gemälde internationaler Künstler – Picasso, Miró und Dalí – vertreten. Heute sind die Ausstellungen des Museums in vier Gebäuden untergebracht.',
          location_de: 'Petrowka-Straße, 25, Jermolajew-Gasse, 17, Gogolewskij-Boulevard, 10 und Twerskoj-Boulevard, 9',
          city_de: 'Moskau',
          workedTime_de: 'Montag - Mittwoch, Freitag - Sonntag von 12:00 bis 20:00',
          holidays_de: 'Donnerstag',
          theme_de: 'Kunst',
        },
        {
          name: 'Государственный исторический музей',
          description:
            'В самом центре столицы, на Красной площади, находится здание Государственного исторического музея, которое сложно не заметить. Краснокирпичное здание, построенное в псевдорусском стиле, напоминает сказочный терем из русских народных сказок. Но если до этого момента вы только любовались им снаружи и не знали что скрывается внутри, то пора уже раскрыть все тайны и заглянуть туда – коллекция музея насчитывает более 5 миллионов предметов, которые рассказывают о политике и культуре России с древнейших времен и до 20 века. Посмотреть стоит на «Родословное древо государей Российских», парадную саблю Наполеона, ископаемые бивни мамонта и залы вpeмeн цapcтвoвaния Eкaтepины Втopoй и Aлeкcaндpa Пepвoгo. Кроме того, в музее выставлены росписи стен и потолков Васнецова, Айвазовского и Репина.',
          location: 'Красная площадь, 1',
          city: 'Москва',
          photo:
            'http://localhost:3000/museumsImages/21_ГосударственныйИсторическийМузей.jpg',
          workedTime:
            'понедельник - пятница с 10:00 до 18:00\n суббота - воскресенье с 10:00 до 21:00',
          holidays: 'без выходных',
          theme: 'История',
          coordinates: '55.75528069242159, 37.61767866637733',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'State Historical Museum',
          description_en: 'In the very center of the capital, on Red Square, stands the building of the State Historical Museum, which is hard to miss. The red brick building, built in pseudo-Russian style, resembles a fairy-tale terem from Russian folk tales. But if until now you have only admired it from the outside and did not know what was inside, it is time to reveal all the secrets and take a look - the museum\'s collection has more than 5 million items that tell about the politics and culture of Russia from ancient times to the 20th century. It is worth looking at the "Genealogical Tree of Russian Sovereigns", Napoleon\'s parade saber, fossil mammoth tusks, and the halls from the reign of Catherine the Great and Alexander I. In addition, the museum exhibits wall and ceiling paintings by Vasnetsov, Aivazovsky, and Repin.',
          location_en: 'Red Square 1',
          city_en: 'Moscow',
          workedTime_en: 'Monday - Friday from 10:00 to 18:00\n Saturday - Sunday from 10:00 to 21:00',
          holidays_en: 'No',
          theme_en: 'History',
          name_de: 'Staatliches Historisches Museum',
          description_de: 'Im Zentrum der Hauptstadt, auf dem Roten Platz, befindet sich das Gebäude des Staatlichen Historischen Museums, das schwer zu übersehen ist. Das rote Ziegelgebäude, das im pseudorussischen Stil gebaut wurde, erinnert an ein Märchenschloss aus russischen Volksmärchen. Wenn Sie es bis jetzt nur von außen bewundert haben und nicht wussten, was sich darin verbirgt, ist es an der Zeit, alle Geheimnisse zu lüften und hineinzuschauen – die Sammlung des Museums umfasst mehr als 5 Millionen Exponate, die die Politik und Kultur Russlands von den ältesten Zeiten bis zum 20. Jahrhundert erzählen. Zu sehen sind der "Stammbaum der russischen Herrscher", Napoleons Paradesäbel, fossile Mammutstoßzähne und die Säle der Herrschaftszeit von Katharina der Großen und Alexander dem Ersten. Darüber hinaus zeigt das Museum Wand- und Deckenmalereien von Wassnezow, Aiwasowski und Repin.',
          location_de: 'Roter Platz, 1',
          city_de: 'Moskau',
          workedTime_de: 'Montag - Freitag von 10:00 bis 18:00\n Samstag - Sonntag von 10:00 bis 21:00',
          holidays_de: 'Keine Ruhetage',
          theme_de: 'Geschichte',
        },
        {
          name: 'Музей Москвы',
          description:
            'Постоянная выставка музея посвящена истории Москвы с древнейших времен и до сегодняшних дней. Рассматривая разные археологические находки, предметы быта и одежду разных исторических эпох, фотографии и архивные документы, вы сможете детально проследить за развитием повседневной жизни москвичей и попробовать представить, что ждет столицу России в будущем. Также в музее представлена серия живописи знаменитых художников, например Васнецова и Айвазовского. Кроме постоянной экспозиции, музей показывает документальные фильмы, проводит лекции и организует творческие занятия для детей.',
          location: 'Зубовский бульвар, 12',
          city: 'Москва',
          photo: 'http://localhost:3000/museumsImages/22_МузейМосквы.jpg',
          workedTime: 'вторник, среда, пятница - воскресенье с 10:00 до 20:00',
          holidays: 'понедельник, четверг',
          theme: 'История',
          coordinates: '55.736390679973496, 37.59359564717745',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'Museum of Moscow',
          description_en: 'The permanent exhibition of the museum is dedicated to the history of Moscow from ancient times to the present day. Looking at various archaeological finds, household items, and clothes from different historical eras, photographs, and archival documents, you will be able to follow the development of everyday life in Moscow in detail and try to imagine what awaits the capital of Russia in the future. The museum also features a series of paintings by famous artists such as Vasnetsov and Aivazovsky. In addition to the permanent exhibition, the museum shows documentaries, lectures, and organizes creative activities for children.',
          location_en: 'Zubovsky Boulevard 12',
          city_en: 'Moscow',
          workedTime_en: 'Tuesday, Wednesday, Friday - Sunday from 10:00 to 20:00',
          holidays_en: 'Monday, Thursday',
          theme_en: 'History',
          name_de: 'Moskauer Museum',
          description_de: 'Die Dauerausstellung des Museums ist der Geschichte Moskaus von den ältesten Zeiten bis heute gewidmet. Beim Betrachten verschiedener archäologischer Funde, Alltagsgegenstände und Kleidung verschiedener historischer Epochen, Fotos und Archivdokumente können Sie die Entwicklung des Alltagslebens der Moskauer im Detail nachverfolgen und versuchen, sich vorzustellen, was die russische Hauptstadt in Zukunft erwartet. Außerdem präsentiert das Museum eine Reihe von Gemälden berühmter Künstler wie Wassnezow und Aiwasowski. Neben der Dauerausstellung zeigt das Museum Dokumentarfilme, hält Vorträge und organisiert kreative Aktivitäten für Kinder.',
          location_de: 'Zubowski-Boulevard, 12',
          city_de: 'Moskau',
          workedTime_de: 'Dienstag, Mittwoch, Freitag - Sonntag von 10:00 bis 20:00',
          holidays_de: 'Montag, Donnerstag',
          theme_de: 'Geschichte',
        },
        {
          name: 'Мемориальный музей космонавтики',
          description:
            'В основании величественного монумента «Покорителям космоса», расположился знаменитый Музей космонавтики, открытый к 20-летию полёта в космос Юрия Гагарина. Среди главных экспонатов музея –первый космический скафандр, чучела Белки и Стрелки, оригинальный пульт управления «Луноходом-1» и «Луноходом-2», личные вещи космонавтов и инженеров. Кроме того, есть и интерактивные экспонаты, например тренажер космического корабля, где можно понять – смогли бы вы стать космонавтом, и мини-центр управления полетами, откуда можно понаблюдать за перемещениями МКС. Также при музее работает кинозал, который имитирует кабину настоящего космического корабля, и тематическое кафе, где можно приобрести пищу космонавтов в тюбиках. Мемориальный музей космонавтики.',
          location: 'проспект Мира, 111',
          city: 'Москва',
          photo:
            'http://localhost:3000/museumsImages/23_МемориальныйМузейКосмонавтики.jpg',
          workedTime: 'вторник - воскресенье с 10:00 до 19:00',
          holidays: 'понедельник',
          theme: 'Наука и техника',
          coordinates: '55.822751068910385, 37.639751499999974',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'Memorial Museum of Cosmonautics',
          description_en: 'At the base of the majestic monument "To the Conquerors of Space" is the famous Museum of Cosmonautics, opened for the 20th anniversary of Yuri Gagarin\'s flight into space. Among the main exhibits of the museum are the first space suit, the stuffed animals of Belka and Strelka, the original control panel of "Lunokhod-1" and "Lunokhod-2", personal belongings of astronauts and engineers. In addition, there are interactive exhibits, such as a spacecraft simulator, where you can find out if you could become an astronaut, and a mini-flight control center where you can observe the movements of the ISS. The museum also has a cinema hall that imitates the cabin of a real spacecraft and a themed cafe where you can buy astronaut food in tubes.',
          location_en: 'Prospekt Mira 111',
          city_en: 'Moscow',
          workedTime_en: 'Tuesday - Sunday from 10:00 to 19:00',
          holidays_en: 'Monday',
          theme_en: 'Science and Technology',
          name_de: 'Memorial Museum der Kosmonautik',
          description_de: 'Im Sockel des majestätischen Denkmals "Eroberer des Weltraums" befindet sich das berühmte Museum der Kosmonautik, das zum 20. Jahrestag des Fluges von Juri Gagarin ins All eröffnet wurde. Zu den wichtigsten Exponaten des Museums gehören der erste Raumanzug, die Präparate von Belka und Strelka, die originalen Steuerpulte des "Lunochod-1" und "Lunochod-2", persönliche Gegenstände von Kosmonauten und Ingenieuren. Darüber hinaus gibt es interaktive Exponate, wie beispielsweise einen Raumfahrzeug-Simulator, bei dem man herausfinden kann, ob man ein Kosmonaut werden könnte, und ein Mini-Kontrollzentrum, von dem aus man die Bewegungen der ISS beobachten kann. Im Museum gibt es auch einen Kinosaal, der das Cockpit eines echten Raumfahrzeugs nachbildet, und ein thematisches Café, in dem man Raumfahrernahrung in Tuben kaufen kann.',
          location_de: 'Prospekt Mira, 111',
          city_de: 'Moskau',
          workedTime_de: 'Dienstag - Sonntag von 10:00 bis 19:00',
          holidays_de: 'Montag',
          theme_de: 'Wissenschaft und Technik',
        },
        {
          name: 'Московский планетарий',
          description:
            'Московский планетарий является старейшим и одним из крупнейших планетариев в России и Европе. Всего в здании четыре уровня, которые включают в себя – Большой и Малый звездный зал, музеи Лунариум и Урании, астрономическую площадку под открытым небом и обсерваторию с самым большим телескопом в Москве, диаметр которого – 300 мм. Так, у вас будет возможность отправиться в настоящее путешествие по мирам Вселенной и Солнечной системы – вы станете свидетелямивулканического извержения, создадите искусственные облака и торнадо, прокатитесь на космическом велосипеде и увидите 9000 космических тел – от планет до падающих звезд.',
          location: 'улица Садовая-Кудринская, 5, строение 1',
          city: 'Москва',
          photo:
            'http://localhost:3000/museumsImages/24_МосковскийПланетарий.jpg',
          workedTime: 'ежедневно с 10:00 до 21:00',
          holidays: 'без выходных',
          theme: 'Наука и техника',
          coordinates: '55.761411068991244, 37.58366099999995',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'Moscow Planetarium',
          description_en: 'The Moscow Planetarium is the oldest and one of the largest planetariums in Russia and Europe. There are four levels in the building, which include the Great and Small Star Halls, the Lunarium and Urania Museums, an open-air astronomical site, and an observatory with the largest telescope in Moscow, with a diameter of 300 mm. Thus, you will have the opportunity to go on a real journey through the worlds of the Universe and the Solar System - you will witness a volcanic eruption, create artificial clouds and tornadoes, ride a space bike and see 9000 celestial bodies - from planets to falling stars.',
          location_en: 'Sadovaya-Kudrinskaya Street 5, Building 1',
          city_en: 'Moscow',
          workedTime_en: 'Daily from 10:00 to 21:00',
          holidays_en: 'No',
          theme_en: 'Science and Technology',
          name_de: 'Moskauer Planetarium',
          description_de: 'Das Moskauer Planetarium ist das älteste und eines der größten Planetarien in Russland und Europa. Das Gebäude umfasst vier Ebenen: den großen und den kleinen Sternensaal, die Museen LUNARIUM und URANIA, eine astronomische Freiluftplattform und eine Sternwarte mit dem größten Teleskop in Moskau, dessen Durchmesser 300 mm beträgt. So haben Sie die Möglichkeit, eine echte Reise durch die Welten des Universums und des Sonnensystems zu unternehmen – Sie werden Zeuge eines Vulkanausbruchs, erstellen künstliche Wolken und Tornados, fahren auf einem kosmischen Fahrrad und sehen 9000 kosmische Objekte – von Planeten bis zu Sternschnuppen.',
          location_de: 'Sadowaja-Kudrinskaja-Straße, 5, Gebäude 1',
          city_de: 'Moskau',
          workedTime_de: 'Täglich von 10:00 bis 21:00',
          holidays_de: 'Keine Ruhetage',
          theme_de: 'Wissenschaft und Technik',
        },
        {
          name: 'Алмазный фонд',
          description:
            'Формироваться алмазный фонд России начал ещё при Петре I и продолжалось вплоть до 1917 года, когда большое количество шедевров распродали большевики. Всё, что уцелело и было возвращено сейчас можно увидеть, посетив одну из многочисленных экскурсий. В музее всего два зала — большой и малый (исторический). В первой представлено коллекция современных изделий — самоцветы, золотые слитки и ювелирные изделия. В историческом можно рассмотреть драгоценности и регалии царского времени — Большая и Малая императорская короны, скипетр и держава Екатерины II, камень с портретом Александра I, алмазы «Орлов» и «Шах», уникальный цейлонский сапфир, изумруд «Зелёная королева», ордена «Золотого Руна» и Андрея Первозванного, диадема-кокошник Марии Фёдоровны, брошь княгини Александры Иосифовны с огранёнными алмазами и колумбийским изумрудом и др.',
          location: 'ул. Манежная, д. 2-10, соор. 3',
          city: 'Москва',
          photo: 'http://localhost:3000/museumsImages/25_АлмазныйФонд.jpg',
          workedTime: 'ежедневно с 10:00 до 17:20',
          holidays: 'без выходных',
          theme: 'Искусство',
          coordinates: '55.74959720379334, 37.61380329950161',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'Diamond Fund',
          description_en: 'The formation of the Diamond Fund of Russia began under Peter I and continued until 1917 when a large number of masterpieces were sold by the Bolsheviks. Everything that survived and was returned can now be seen by visiting one of the many excursions. The museum has only two halls - large and small (historical). The first presents a collection of modern items - gems, gold bars, and jewelry. In the historical one, you can see the jewels and regalia of the tsarist times - the Large and Small Imperial Crowns, the scepter and orb of Catherine II, the stone with the portrait of Alexander I, the diamonds "Orlov" and "Shah", the unique Ceylon sapphire, the emerald "Green Queen", the orders of the "Golden Fleece" and Andrew the First-Called, the diadem-cockade of Maria Feodorovna, the brooch of Princess Alexandra Iosifovna with cut diamonds and a Colombian emerald, and others.',
          location_en: 'Manezhnaya Street 2-10, Building 3',
          city_en: 'Moscow',
          workedTime_en: 'Daily from 10:00 to 17:20',
          holidays_en: 'No',
          theme_en: 'Art',
          name_de: 'Diamantenfonds',
          description_de: 'Der Diamantenfonds Russlands begann sich noch unter Peter I. zu formieren und dauerte bis 1917, als viele Meisterwerke von den Bolschewiki verkauft wurden. Alles, was erhalten geblieben und zurückgegeben worden ist, kann jetzt bei einer der zahlreichen Führungen besichtigt werden. Das Museum besteht aus zwei Sälen – dem großen und dem kleinen (historischen) Saal. Im ersten wird eine Sammlung moderner Stücke präsentiert – Edelsteine, Goldbarren und Schmuckstücke. Im historischen Saal können Sie die Juwelen und Insignien der Zarenzeit betrachten – die große und die kleine Kaiserkrone, das Zepter und den Reichsapfel von Katharina II., einen Stein mit dem Porträt von Alexander I., die Diamanten "Orlow" und "Schah", den einzigartigen Ceylon-Saphir, den Smaragd "Grüne Königin", die Orden des "Goldenen Vlieses" und des heiligen Andreas des Erstberufenen, das Diadem-Kokoshnik von Maria Fjodorowna, die Brosche der Fürstin Alexandra Iossifowna mit geschliffenen Diamanten und kolumbianischem Smaragd und vieles mehr.',
          location_de: 'Maneschnaja-Straße, Gebäude 2-10, Bauwerk 3',
          city_de: 'Moskau',
          workedTime_de: 'Täglich von 10:00 bis 17:20',
          holidays_de: 'Keine Ruhetage',
          theme_de: 'Kunst',
        },
        {
          name: 'Музей ГЭС-2',
          description:
            'Свое существование музей начал не так давно, но уже стал постоянной площадкой фонда поддержки современного искусства. Культурное пространство расположилось в здании, где ранее была электростанция и сегодня там проходят лекции и кинопоказы, а также временные выставки и различные мастер-классы, концерты и мероприятия для детей. Здесь же созданы условия для поддержки художественного сообщества.',
          location: 'Болотная наб., 15, корп. 1',
          city: 'Москва',
          photo: 'http://localhost:3000/museumsImages/26_ГЭС2.jpg',
          workedTime: 'ежедневно с 11:00 до 22:00',
          holidays: 'без выходных',
          theme: 'Искусство',
          coordinates: '55.742776153509794, 37.61272513558195',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'GES-2 Museum',
          description_en: 'The museum began its existence not so long ago, but it has already become a permanent platform for the Foundation for the Support of Contemporary Art. The cultural space is located in a building that was previously a power station, and today lectures and film screenings, as well as temporary exhibitions and various workshops, concerts, and children\'s events, are held there. Conditions have also been created here to support the art community.',
          location_en: 'Bolotnaya Embankment 15, Building 1',
          city_en: 'Moscow',
          workedTime_en: 'Daily from 11:00 to 22:00',
          holidays_en: 'No',
          theme_en: 'Art',
          name_de: 'GES-2 Museum',
          description_de: 'Das Museum existiert noch nicht lange, aber es ist bereits ein ständiger Standort der Stiftung zur Förderung zeitgenössischer Kunst geworden. Der Kulturraum befindet sich in einem Gebäude, in dem früher ein Kraftwerk war, und heute finden dort Vorträge und Filmvorführungen sowie temporäre Ausstellungen und verschiedene Meisterklassen, Konzerte und Veranstaltungen für Kinder statt. Hier wurden auch Bedingungen zur Unterstützung der künstlerischen Gemeinschaft geschaffen.',
          location_de: 'Bolotnaja-Uferstraße, 15, Gebäude 1',
          city_de: 'Moskau',
          workedTime_de: 'Täglich von 11:00 bis 22:00',
          holidays_de: 'Keine Ruhetage',
          theme_de: 'Kunst',
        },
        {
          name: 'Оружейная палата',
          description:
            'Московская Оружейная палата расположена в здании, построенном в середине XIX в. в её фондах хранится больше 4 тысяч экспонатов, относящихся к XII-XIX векам. Основную часть коллекции составляют предметы, ранее находившиеся в царской казне, в том числе и являющиеся дарами иностранных послов.',
          location: 'ул. Манежная, д. 2-10, соор. 3',
          city: 'Москва',
          photo: 'http://localhost:3000/museumsImages/27_ОружейнаяПалата.jpg',
          workedTime: 'ежедневно с 10:00 до 16:30',
          holidays: 'без выходных',
          theme: 'История',
          coordinates: '55.74945279754071, 37.61347886451284',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'Armoury Chamber',
          description_en: 'The Moscow Armoury Chamber is located in a building built in the mid-19th century. Its funds contain more than 4 thousand exhibits dating back to the 12th-19th centuries. The main part of the collection consists of items previously in the royal treasury, including those that were gifts from foreign ambassadors.',
          location_en: 'Manezhnaya Street 2-10, Building 3',
          city_en: 'Moscow',
          workedTime_en: 'Daily from 10:00 to 16:30',
          holidays_en: 'No',
          theme_en: 'History',
          name_de: 'Waffenkammer',
          description_de: 'Die Moskauer Waffenkammer befindet sich in einem Gebäude, das Mitte des 19. Jahrhunderts erbaut wurde. In ihren Beständen befinden sich mehr als 4.000 Exponate aus dem 12. bis 19. Jahrhundert. Den größten Teil der Sammlung bilden Gegenstände, die sich früher im kaiserlichen Schatz befanden, darunter Geschenke ausländischer Botschafter.',
          location_de: 'Maneschnaja-Straße, Gebäude 2-10, Bauwerk 3',
          city_de: 'Moskau',
          workedTime_de: 'Täglich von 10:00 bis 16:30',
          holidays_de: 'Keine Ruhetage',
          theme_de: 'Geschichte',
        },
        {
          name: 'Палеонтологический музей имени Ю. А. Орло́ва РАН',
          description:
            'Палеонтологический музей имени Ю. А. Орло́ва РАН — московский музей, один из крупнейших естественно-исторических музеев мира. Был основан в 1937 году, с 1966 года назван в честь зоолога и палеонтолога Юрия Орлова. Музей является частью Палеонтологического института имени А. А. Борисяка.',
          location: 'ул. Профсоюзная, 123',
          city: 'Москва',
          photo:
            'http://localhost:3000/museumsImages/28_ПалеонтологическийМузей.jpg',
          workedTime: 'ежедневно с 10:00 до 18:00',
          holidays: 'без выходных',
          theme: 'Природа и животные',
          coordinates: '55.62397738636137, 37.513893948410015',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'Orlov Paleontological Museum of the Russian Academy of Sciences',
          description_en: 'The Orlov Paleontological Museum of the Russian Academy of Sciences is a Moscow museum, one of the largest natural history museums in the world. It was founded in 1937, and since 1966 has been named after the zoologist and paleontologist Yuri Orlov. The museum is part of the A.A. Borisyak Paleontological Institute.',
          location_en: 'Profsoyuznaya Street 123',
          city_en: 'Moscow',
          workedTime_en: 'Daily from 10:00 to 18:00',
          holidays_en: 'No',
          theme_en: 'Nature',
          name_de: 'Paläontologisches Museum benannt nach J. A. Orlow der Russischen Akademie der Wissenschaften',
          description_de: 'Das Paläontologische Museum benannt nach J. A. Orlow der Russischen Akademie der Wissenschaften ist eines der größten naturhistorischen Museen der Welt. Es wurde 1937 gegründet und trägt seit 1966 den Namen des Zoologen und Paläontologen Juri Orlow. Das Museum ist Teil des Paläontologischen Instituts benannt nach A. A. Borissjak.',
          location_de: 'Prospekt Mira, 111',
          city_de: 'Moskau',
          workedTime_de: 'Täglich von 10:00 bis 18:00',
          holidays_de: 'Keine Ruhetage',
          theme_de: 'Wissenschaft und Technik',
        },
        {
          name: 'Музей Московских стрельцов (Стрелецкие палаты)',
          description:
            'Стрелецкие палаты — интерактивная познавательная площадка для знатоков и любителей военной истории. На базе музея представлены две постоянные экспозиции: «Московские стрельцы» и «Служилые люди государства Московского». А также есть множество исторических выставок, тематических программ и экскурсий, которые постоянно меняются и обновляются.',
          location: 'Лаврушинский пер., 17, стр. 1',
          city: 'Москва',
          photo: 'http://localhost:3000/museumsImages/29_СтрелецкиеПалаты.jpg',
          workedTime: 'ежедневно с 10:00 до 17:00',
          holidays: 'без выходных',
          theme: 'История',
          coordinates: '55.74112370142079, 37.622385415344226',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'Museum of the Moscow Streltsy (Streltsy Chambers)',
          description_en: 'The Streltsy Chambers is an interactive educational platform for connoisseurs and lovers of military history. The museum houses two permanent exhibitions: "Moscow Streltsy" and "Service People of the Moscow State". There are also many historical exhibitions, thematic programs, and excursions that are constantly changing and being updated.',
          location_en: 'Lavrushinsky Lane 17, Building 1',
          city_en: 'Moscow',
          workedTime_en: 'Daily from 10:00 to 17:00',
          holidays_en: 'No',
          theme_en: 'History',
          name_de: 'Museum der Moskauer Schützen (Streletzkije Palaty)',
          description_de: 'Die Streletzkije Palaty sind eine interaktive Bildungsplattform für Kenner und Liebhaber der Militärgeschichte. Das Museum zeigt zwei Dauerausstellungen: "Die Moskauer Schützen" und "Die Dienstleute des Moskauer Staates". Es gibt auch zahlreiche historische Ausstellungen, thematische Programme und Führungen, die ständig wechseln und aktualisiert werden.',
          location_de: 'Lawruschinski-Gasse, 17, Gebäude 1',
          city_de: 'Moskau',
          workedTime_de: 'Täglich von 10:00 bis 17:00',
          holidays_de: 'Keine Ruhetage',
          theme_de: 'Geschichte',
        },
        {
          name: 'Музей русского импрессионизма',
          description:
            'Музейный комплекс позволяет посетителям ознакомиться с творчеством своих соотечественников — мастеров импрессионизма, работы которых были незаслуженно позабыты. Для изучения представлена постоянная экспозиция, а также проходят выставки, где можно увидеть картины, хранящиеся в частных коллекциях и государственных собраниях. Музей плотно сотрудничает с Третьяковской галереей и Русским музеем.',
          location: 'Ленинградский просп., 15, стр. 11',
          city: 'Москва',
          photo:
            'http://localhost:3000/museumsImages/30_МузейРусскогоИмпрессионизма.jpg',
          workedTime:
            'понедельник - вторник с 12:00 до 20:00,\n пятница - воскресенье с 11:00 до 20:00',
          holidays: 'среда, четверг',
          theme: 'История',
          coordinates: '55.78035797617814, 37.57038710185241',
          createdAt: new Date(),
          updatedAt: new Date(),
          name_en: 'Museum of Russian Impressionism',
          description_en: 'The museum complex allows visitors to get acquainted with the work of their compatriots - masters of impressionism, whose works were undeservedly forgotten. The permanent exhibition is presented for study, and exhibitions are held where you can see paintings stored in private collections and state collections. The museum closely cooperates with the Tretyakov Gallery and the Russian Museum.',
          location_en: 'Leningradsky Prospekt 15, Building 11',
          city_en: 'Moscow',
          workedTime_en: 'Monday - Tuesday from 12:00 to 20:00,\n Friday - Sunday from 11:00 to 20:00',
          holidays_en: 'Wednesday, Thursday',
          theme_en: 'History',
          name_de: 'Museum des Russischen Impressionismus',
          description_de: 'Der Museumskomplex ermöglicht es den Besuchern, sich mit den Werken ihrer Landsleute – Meister des Impressionismus – vertraut zu machen, deren Arbeiten zu Unrecht in Vergessenheit geraten sind. Es gibt eine Dauerausstellung und Wechselausstellungen, bei denen Gemälde gezeigt werden, die sich in Privat- und Staatssammlungen befinden. Das Museum arbeitet eng mit der Tretjakow-Galerie und dem Russischen Museum zusammen.',
          location_de: 'Leningradski-Prospekt, 15, Gebäude 11',
          city_de: 'Moskau',
          workedTime_de: 'Montag - Dienstag von 12:00 bis 20:00,\n Freitag - Sonntag von 11:00 bis 20:00',
          holidays_de: 'Mittwoch, Donnerstag',
          theme_de: 'Geschichte',
        },
      ],
      {},
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Museums', null, {});
  },
};
